/**
 * This class is generated by jOOQ
 */
package com.donde.adv.tour.domain.tables;


import com.donde.adv.tour.domain.Keys;
import com.donde.adv.tour.domain.Public;
import com.donde.adv.tour.domain.tables.records.FastCreditCommentRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * Tabla para comentarios de crditos giles
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FastCreditComment extends TableImpl<FastCreditCommentRecord> {

	private static final long serialVersionUID = 895063954;

	/**
	 * The reference instance of <code>public.advtour_fast_credit_comment</code>
	 */
	public static final FastCreditComment ADVTOUR_FAST_CREDIT_COMMENT = new FastCreditComment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FastCreditCommentRecord> getRecordType() {
		return FastCreditCommentRecord.class;
	}

	/**
	 * The column <code>public.advtour_fast_credit_comment.sap_id</code>. Identificador de sap
	 */
	public final TableField<FastCreditCommentRecord, String> SAP_ID = createField("sap_id", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false), this, "Identificador de sap");

	/**
	 * The column <code>public.advtour_fast_credit_comment.fast_credit_id</code>. Identificador de solicitud de crdito
	 */
	public final TableField<FastCreditCommentRecord, Integer> FAST_CREDIT_ID = createField("fast_credit_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Identificador de solicitud de crdito");

	/**
	 * The column <code>public.advtour_fast_credit_comment.created_by</code>. Creado por
	 */
	public final TableField<FastCreditCommentRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "Creado por");

	/**
	 * The column <code>public.advtour_fast_credit_comment.created_at</code>. Creado el
	 */
	public final TableField<FastCreditCommentRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "Creado el");

	/**
	 * The column <code>public.advtour_fast_credit_comment.comment</code>. Comentario
	 */
	public final TableField<FastCreditCommentRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "Comentario");

	/**
	 * Create a <code>public.advtour_fast_credit_comment</code> table reference
	 */
	public FastCreditComment() {
		this("advtour_fast_credit_comment", null);
	}

	/**
	 * Create an aliased <code>public.advtour_fast_credit_comment</code> table reference
	 */
	public FastCreditComment(String alias) {
		this(alias, ADVTOUR_FAST_CREDIT_COMMENT);
	}

	private FastCreditComment(String alias, Table<FastCreditCommentRecord> aliased) {
		this(alias, aliased, null);
	}

	private FastCreditComment(String alias, Table<FastCreditCommentRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "Tabla para comentarios de crditos giles");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<FastCreditCommentRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<FastCreditCommentRecord, ?>>asList(Keys.ADVTOUR_FAST_CREDIT_COMMENT__FK_ADVTOUR_FAST_CREDIT_COMMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FastCreditComment as(String alias) {
		return new FastCreditComment(alias, this);
	}

	/**
	 * Rename this table
	 */
	public FastCreditComment rename(String name) {
		return new FastCreditComment(name, null);
	}
}
