/**
 * This class is generated by jOOQ
 */
package com.donde.adv.tour.domain.tables;


import com.donde.adv.tour.domain.Keys;
import com.donde.adv.tour.domain.Public;
import com.donde.adv.tour.domain.tables.records.FastCreditRequestRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Tabla para crditos giles
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FastCreditRequest extends TableImpl<FastCreditRequestRecord> {

	private static final long serialVersionUID = 220832478;

	/**
	 * The reference instance of <code>public.advtour_fast_credit_request</code>
	 */
	public static final FastCreditRequest ADVTOUR_FAST_CREDIT_REQUEST = new FastCreditRequest();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FastCreditRequestRecord> getRecordType() {
		return FastCreditRequestRecord.class;
	}

	/**
	 * The column <code>public.advtour_fast_credit_request.sap_id</code>. Identificador de sap
	 */
	public final TableField<FastCreditRequestRecord, String> SAP_ID = createField("sap_id", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false), this, "Identificador de sap");

	/**
	 * The column <code>public.advtour_fast_credit_request.fast_credit_id</code>. Identificador de solicitud de crdito
	 */
	public final TableField<FastCreditRequestRecord, Integer> FAST_CREDIT_ID = createField("fast_credit_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Identificador de solicitud de crdito");

	/**
	 * The column <code>public.advtour_fast_credit_request.cust_id</code>. Cliente del crdito
	 */
	public final TableField<FastCreditRequestRecord, String> CUST_ID = createField("cust_id", org.jooq.impl.SQLDataType.CHAR.length(10).nullable(false), this, "Cliente del crdito");

	/**
	 * The column <code>public.advtour_fast_credit_request.payer_id</code>. Pagador del crdito
	 */
	public final TableField<FastCreditRequestRecord, Integer> PAYER_ID = createField("payer_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Pagador del crdito");

	/**
	 * The column <code>public.advtour_fast_credit_request.center</code>. Centro de captura
	 */
	public final TableField<FastCreditRequestRecord, String> CENTER = createField("center", org.jooq.impl.SQLDataType.CHAR.length(4).nullable(false), this, "Centro de captura");

	/**
	 * The column <code>public.advtour_fast_credit_request.route</code>. Ruta de captura
	 */
	public final TableField<FastCreditRequestRecord, String> ROUTE = createField("route", org.jooq.impl.SQLDataType.CHAR.length(6).nullable(false), this, "Ruta de captura");

	/**
	 * The column <code>public.advtour_fast_credit_request.sales_person</code>. Agente de ventas de captura
	 */
	public final TableField<FastCreditRequestRecord, String> SALES_PERSON = createField("sales_person", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "Agente de ventas de captura");

	/**
	 * The column <code>public.advtour_fast_credit_request.cust_name</code>. Nombre del solicitante
	 */
	public final TableField<FastCreditRequestRecord, String> CUST_NAME = createField("cust_name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "Nombre del solicitante");

	/**
	 * The column <code>public.advtour_fast_credit_request.email</code>. Emial del solicitante
	 */
	public final TableField<FastCreditRequestRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "Emial del solicitante");

	/**
	 * The column <code>public.advtour_fast_credit_request.phone</code>. Telfono del solicitante
	 */
	public final TableField<FastCreditRequestRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "Telfono del solicitante");

	/**
	 * The column <code>public.advtour_fast_credit_request.rfc</code>. RFC del solicitante
	 */
	public final TableField<FastCreditRequestRecord, String> RFC = createField("rfc", org.jooq.impl.SQLDataType.CHAR.length(16).nullable(false), this, "RFC del solicitante");

	/**
	 * The column <code>public.advtour_fast_credit_request.extra_name_1</code>. Nombre de otro encargado
	 */
	public final TableField<FastCreditRequestRecord, String> EXTRA_NAME_1 = createField("extra_name_1", org.jooq.impl.SQLDataType.CLOB, this, "Nombre de otro encargado");

	/**
	 * The column <code>public.advtour_fast_credit_request.extra_birthdate_1</code>. Fecha de nacimiento de otro encargado
	 */
	public final TableField<FastCreditRequestRecord, Timestamp> EXTRA_BIRTHDATE_1 = createField("extra_birthdate_1", org.jooq.impl.SQLDataType.TIMESTAMP, this, "Fecha de nacimiento de otro encargado");

	/**
	 * The column <code>public.advtour_fast_credit_request.extra_name_2</code>. Nombre de otro encargado
	 */
	public final TableField<FastCreditRequestRecord, String> EXTRA_NAME_2 = createField("extra_name_2", org.jooq.impl.SQLDataType.CLOB, this, "Nombre de otro encargado");

	/**
	 * The column <code>public.advtour_fast_credit_request.extra_birthdate_2</code>. Fecha de nacimiento de otro encargado
	 */
	public final TableField<FastCreditRequestRecord, Timestamp> EXTRA_BIRTHDATE_2 = createField("extra_birthdate_2", org.jooq.impl.SQLDataType.TIMESTAMP, this, "Fecha de nacimiento de otro encargado");

	/**
	 * The column <code>public.advtour_fast_credit_request.supervised_by</code>. Supervisor que aprueba la solicitud
	 */
	public final TableField<FastCreditRequestRecord, String> SUPERVISED_BY = createField("supervised_by", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "Supervisor que aprueba la solicitud");

	/**
	 * The column <code>public.advtour_fast_credit_request.approved_by</code>. Administrativo que aprueba la solicitud
	 */
	public final TableField<FastCreditRequestRecord, String> APPROVED_BY = createField("approved_by", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "Administrativo que aprueba la solicitud");

	/**
	 * The column <code>public.advtour_fast_credit_request.credit_ammount</code>. Monto de crdito
	 */
	public final TableField<FastCreditRequestRecord, BigDecimal> CREDIT_AMMOUNT = createField("credit_ammount", org.jooq.impl.SQLDataType.NUMERIC.precision(10, 3).nullable(false), this, "Monto de crdito");

	/**
	 * The column <code>public.advtour_fast_credit_request.credit_days</code>. Das de crdito
	 */
	public final TableField<FastCreditRequestRecord, Integer> CREDIT_DAYS = createField("credit_days", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Das de crdito");

	/**
	 * The column <code>public.advtour_fast_credit_request.status_request</code>.
	 */
	public final TableField<FastCreditRequestRecord, Integer> STATUS_REQUEST = createField("status_request", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.advtour_fast_credit_request.motive_reject</code>.
	 */
	public final TableField<FastCreditRequestRecord, Integer> MOTIVE_REJECT = createField("motive_reject", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.advtour_fast_credit_request.created_at</code>. Fecha de creacin
	 */
	public final TableField<FastCreditRequestRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "Fecha de creacin");

	/**
	 * The column <code>public.advtour_fast_credit_request.updated_at</code>. Fecha de modificacin
	 */
	public final TableField<FastCreditRequestRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "Fecha de modificacin");

	/**
	 * The column <code>public.advtour_fast_credit_request.delta</code>. Delta para sincronizacin
	 */
	public final TableField<FastCreditRequestRecord, Long> DELTA = createField("delta", org.jooq.impl.SQLDataType.BIGINT.defaulted(true), this, "Delta para sincronizacin");

	/**
	 * Create a <code>public.advtour_fast_credit_request</code> table reference
	 */
	public FastCreditRequest() {
		this("advtour_fast_credit_request", null);
	}

	/**
	 * Create an aliased <code>public.advtour_fast_credit_request</code> table reference
	 */
	public FastCreditRequest(String alias) {
		this(alias, ADVTOUR_FAST_CREDIT_REQUEST);
	}

	private FastCreditRequest(String alias, Table<FastCreditRequestRecord> aliased) {
		this(alias, aliased, null);
	}

	private FastCreditRequest(String alias, Table<FastCreditRequestRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "Tabla para crditos giles");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<FastCreditRequestRecord> getPrimaryKey() {
		return Keys.PK_ADVTOUR_FAST_CREDIT_REQUEST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<FastCreditRequestRecord>> getKeys() {
		return Arrays.<UniqueKey<FastCreditRequestRecord>>asList(Keys.PK_ADVTOUR_FAST_CREDIT_REQUEST);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FastCreditRequest as(String alias) {
		return new FastCreditRequest(alias, this);
	}

	/**
	 * Rename this table
	 */
	public FastCreditRequest rename(String name) {
		return new FastCreditRequest(name, null);
	}
}
