/**
 * This class is generated by jOOQ
 */
package com.donde.adv.tour.domain.tables;


import com.donde.adv.tour.domain.Keys;
import com.donde.adv.tour.domain.Public;
import com.donde.adv.tour.domain.tables.records.FreedisCampaignHeaderRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Tabla para cabecera de campaa de freedis
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FreedisCampaignHeader extends TableImpl<FreedisCampaignHeaderRecord> {

	private static final long serialVersionUID = -1631414129;

	/**
	 * The reference instance of <code>public.advtour_freedis_campaign_header</code>
	 */
	public static final FreedisCampaignHeader ADVTOUR_FREEDIS_CAMPAIGN_HEADER = new FreedisCampaignHeader();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FreedisCampaignHeaderRecord> getRecordType() {
		return FreedisCampaignHeaderRecord.class;
	}

	/**
	 * The column <code>public.advtour_freedis_campaign_header.sap_id</code>. Identificador de sap
	 */
	public final TableField<FreedisCampaignHeaderRecord, String> SAP_ID = createField("sap_id", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false), this, "Identificador de sap");

	/**
	 * The column <code>public.advtour_freedis_campaign_header.freedis_campaign_id</code>. Identificador de la cabecera de campaa
	 */
	public final TableField<FreedisCampaignHeaderRecord, Integer> FREEDIS_CAMPAIGN_ID = createField("freedis_campaign_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Identificador de la cabecera de campaa");

	/**
	 * The column <code>public.advtour_freedis_campaign_header.name</code>. Nombre
	 */
	public final TableField<FreedisCampaignHeaderRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "Nombre");

	/**
	 * The column <code>public.advtour_freedis_campaign_header.motive</code>. Motivo
	 */
	public final TableField<FreedisCampaignHeaderRecord, String> MOTIVE = createField("motive", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "Motivo");

	/**
	 * The column <code>public.advtour_freedis_campaign_header.started_at</code>. Fecha de inicio de validez
	 */
	public final TableField<FreedisCampaignHeaderRecord, Timestamp> STARTED_AT = createField("started_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "Fecha de inicio de validez");

	/**
	 * The column <code>public.advtour_freedis_campaign_header.ended_at</code>. Fecha de fin de validez
	 */
	public final TableField<FreedisCampaignHeaderRecord, Timestamp> ENDED_AT = createField("ended_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "Fecha de fin de validez");

	/**
	 * The column <code>public.advtour_freedis_campaign_header.created_at</code>. Fecha de creacion de la campaa
	 */
	public final TableField<FreedisCampaignHeaderRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "Fecha de creacion de la campaa");

	/**
	 * The column <code>public.advtour_freedis_campaign_header.created_by</code>. Usuario quien creo la campaa
	 */
	public final TableField<FreedisCampaignHeaderRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "Usuario quien creo la campaa");

	/**
	 * The column <code>public.advtour_freedis_campaign_header.updated_at</code>. Fecha de la ultima modificacion de la campaa
	 */
	public final TableField<FreedisCampaignHeaderRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "Fecha de la ultima modificacion de la campaa");

	/**
	 * The column <code>public.advtour_freedis_campaign_header.updated_by</code>. usuario quie modifico la campaa
	 */
	public final TableField<FreedisCampaignHeaderRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "usuario quie modifico la campaa");

	/**
	 * The column <code>public.advtour_freedis_campaign_header.is_deleted</code>. Bandera de borrado
	 */
	public final TableField<FreedisCampaignHeaderRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "Bandera de borrado");

	/**
	 * The column <code>public.advtour_freedis_campaign_header.delta</code>. Delta de actualizacin
	 */
	public final TableField<FreedisCampaignHeaderRecord, Long> DELTA = createField("delta", org.jooq.impl.SQLDataType.BIGINT, this, "Delta de actualizacin");

	/**
	 * Create a <code>public.advtour_freedis_campaign_header</code> table reference
	 */
	public FreedisCampaignHeader() {
		this("advtour_freedis_campaign_header", null);
	}

	/**
	 * Create an aliased <code>public.advtour_freedis_campaign_header</code> table reference
	 */
	public FreedisCampaignHeader(String alias) {
		this(alias, ADVTOUR_FREEDIS_CAMPAIGN_HEADER);
	}

	private FreedisCampaignHeader(String alias, Table<FreedisCampaignHeaderRecord> aliased) {
		this(alias, aliased, null);
	}

	private FreedisCampaignHeader(String alias, Table<FreedisCampaignHeaderRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "Tabla para cabecera de campaa de freedis");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<FreedisCampaignHeaderRecord> getPrimaryKey() {
		return Keys.PK_ADVTOUR_FREEDIS_CAMPAIGN_HEADER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<FreedisCampaignHeaderRecord>> getKeys() {
		return Arrays.<UniqueKey<FreedisCampaignHeaderRecord>>asList(Keys.PK_ADVTOUR_FREEDIS_CAMPAIGN_HEADER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FreedisCampaignHeader as(String alias) {
		return new FreedisCampaignHeader(alias, this);
	}

	/**
	 * Rename this table
	 */
	public FreedisCampaignHeader rename(String name) {
		return new FreedisCampaignHeader(name, null);
	}
}
