/**
 * This class is generated by jOOQ
 */
package com.donde.adv.tour.domain.tables;


import com.donde.adv.tour.domain.Keys;
import com.donde.adv.tour.domain.Public;
import com.donde.adv.tour.domain.tables.records.FreedisCampaignMaterialRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Tabla para materiales de las campaas de freedis
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FreedisCampaignMaterial extends TableImpl<FreedisCampaignMaterialRecord> {

	private static final long serialVersionUID = -1425388475;

	/**
	 * The reference instance of <code>public.advtour_freedis_campaign_material</code>
	 */
	public static final FreedisCampaignMaterial ADVTOUR_FREEDIS_CAMPAIGN_MATERIAL = new FreedisCampaignMaterial();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FreedisCampaignMaterialRecord> getRecordType() {
		return FreedisCampaignMaterialRecord.class;
	}

	/**
	 * The column <code>public.advtour_freedis_campaign_material.sap_id</code>. Identificador de sap
	 */
	public final TableField<FreedisCampaignMaterialRecord, String> SAP_ID = createField("sap_id", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false), this, "Identificador de sap");

	/**
	 * The column <code>public.advtour_freedis_campaign_material.freedis_campaign_id</code>. Identificador de la campaa de freedis
	 */
	public final TableField<FreedisCampaignMaterialRecord, Integer> FREEDIS_CAMPAIGN_ID = createField("freedis_campaign_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Identificador de la campaa de freedis");

	/**
	 * The column <code>public.advtour_freedis_campaign_material.matnr_id</code>. Identificador del material
	 */
	public final TableField<FreedisCampaignMaterialRecord, String> MATNR_ID = createField("matnr_id", org.jooq.impl.SQLDataType.CHAR.length(18).nullable(false), this, "Identificador del material");

	/**
	 * The column <code>public.advtour_freedis_campaign_material.is_deleted</code>. Bandera de borrado
	 */
	public final TableField<FreedisCampaignMaterialRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "Bandera de borrado");

	/**
	 * The column <code>public.advtour_freedis_campaign_material.delta</code>. Delta de actualizacin
	 */
	public final TableField<FreedisCampaignMaterialRecord, Long> DELTA = createField("delta", org.jooq.impl.SQLDataType.BIGINT, this, "Delta de actualizacin");

	/**
	 * Create a <code>public.advtour_freedis_campaign_material</code> table reference
	 */
	public FreedisCampaignMaterial() {
		this("advtour_freedis_campaign_material", null);
	}

	/**
	 * Create an aliased <code>public.advtour_freedis_campaign_material</code> table reference
	 */
	public FreedisCampaignMaterial(String alias) {
		this(alias, ADVTOUR_FREEDIS_CAMPAIGN_MATERIAL);
	}

	private FreedisCampaignMaterial(String alias, Table<FreedisCampaignMaterialRecord> aliased) {
		this(alias, aliased, null);
	}

	private FreedisCampaignMaterial(String alias, Table<FreedisCampaignMaterialRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "Tabla para materiales de las campaas de freedis");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<FreedisCampaignMaterialRecord> getPrimaryKey() {
		return Keys.PK_ADVTOUR_FREEDIS_CAMPAIGN_MATERIAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<FreedisCampaignMaterialRecord>> getKeys() {
		return Arrays.<UniqueKey<FreedisCampaignMaterialRecord>>asList(Keys.PK_ADVTOUR_FREEDIS_CAMPAIGN_MATERIAL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<FreedisCampaignMaterialRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<FreedisCampaignMaterialRecord, ?>>asList(Keys.ADVTOUR_FREEDIS_CAMPAIGN_MATERIAL__FK_ADVTOUR_FREEDIS_CAMPAIGN_MATERIAL_HEADER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FreedisCampaignMaterial as(String alias) {
		return new FreedisCampaignMaterial(alias, this);
	}

	/**
	 * Rename this table
	 */
	public FreedisCampaignMaterial rename(String name) {
		return new FreedisCampaignMaterial(name, null);
	}
}
